blank_issues_enabled: false
contact_links:
  - name: I have a question or need support
    url: https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions
    about: Use Github Discussions to find support and ask general questions
